def reverseComplement(sequence):
    seq= sequence
    seq_backward = seq[::-1] 
    base_partners = {"A":"T", "C":"G", "G":"C", "T":"A"} 
    seq_converted = ""  
    
    for char in seq_backward: #Loop through and look up the complement to create the new sequence
        seq_converted += base_partners[char]

    return seq_converted
    

seq = 'CGCTGCAGAACGTAACGCGTTCGTCTATTCACAGTTGATTTTCATTAGATCGCGCTAAGCTGTTTTCCAACACATCGGTAATGCTCACAGGTAATCATGATCCGTCGGGTGGAACATCCTGACTTTTTAAGGGATGCAGTGGCTCTGTCGTATCAACTTACGTTTTATCTAACTTCCATGTTTTTGACATCCCAAAGGGGGCTCGCTGCCTCGCAATGTACCATCTGGATACGTCGAAAGTACAATAAGATTATAGAAGCGCTTTTATGACCACTCGGAAAGAGAGCACGATGGGCCCGAGCTCGGAGTCGAGGTATCTGGGGGAAGTTGACTACCCAGGGACGCATCGCAGGAGACTTCGATCTTCGGGTTACTCTAAGCTGATAACACCGGGGTCCGTACTCACTTACTACGTCCGCTGCGTCGCGCAGCGCTAGGAAGAGCTCTTCAGGTTTCGGGGTGGGACGATATCGCCACTCTTGTGATCCCGTATGTAATATGAAAAGGTGACCTGACGGGCGGGTGACCTTTCACAATGCCACAAGACACGCTTTATCTAACCTCAATAGTGACAGCAGAGCGCCAAGAACGAACCCGGAAGGCTCGGCTACTAGGAATCGCAGGTCGTCTGAGGCTTATCCCAGGTGTCTGGCCATAGCGGGTCAAGGATACTAAGAAATGTATCCCGTATTCTCCCATTATAAGCGGCACCTATTTGTCAGGGTAAGCGTATTTTTTCCTCGGAGGTGGGAGGCTAAATTAGATTGACCTGTTGTGTGTCTACTTATTAACAGCTAAACATGGGGTGCTGGCATTTCTCTAACGACCACAGATT'
print reverseComplement(seq)